# Generated by Django 5.1.5 on 2025-01-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PmidKeywords",
            fields=[
                ("pmid", models.IntegerField(primary_key=True, serialize=False)),
                ("keyword_info", models.JSONField()),
            ],
            options={
                "db_table": "pmid_keywords",
            },
        ),
    ]
