# Generated by Django 5.1.5 on 2025-01-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_assignment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="pmidkeywords",
            table=None,
        ),
    ]
